export default data = [
    //happy
    [
        require('../resources/imgs/cuteKitten.jpg'),
        require('../resources/imgs/happyBalloons.jpg')
    ],
    //disgusted
    [
        require('../resources/imgs/intestine.jpg'),
        require('../resources/imgs/donaldTrump.jpg'),
    ],
    //angry
    [
        require('../resources/imgs/codeError.jpg'),
        require('../resources/imgs/doctorConspiracy.jpg'),
    ],
    //surprised
    [
        require('../resources/imgs/sheepFact.jpg'),
        require('../resources/imgs/mongooseProblem.jpg'),

    ],
    //contemptuous
    [
        require('../resources/imgs/sunStaring.jpg'),
        require('../resources/imgs/heavyLaptop.jpg'),
        require('../resources/imgs/jesusResurrection.jpg')
    ],
    //sad
    [
        require('../resources/imgs/globalWarming.jpg'),
        require('../resources/imgs/starvingChildren.jpg'),
    ]
]